[2018-08-27 Mon 16:28:49]fuzztask.py-12992-140229360850688-34-    INFO-"Thread-81 FUZZ检测任务启动2018-08-27 16:28:49.306461"
[2018-08-27 Mon 16:28:49]fuzztask.py-12992-140229356644096-34-    INFO-"Thread-82 FUZZ检测任务启动2018-08-27 16:28:49.387152"
[2018-08-27 Mon 16:28:49]fuzztask.py-12992-140229360850688-49-    INFO-"FUZZ检测:   113.105.74.144:80,http"
[2018-08-27 Mon 16:28:49]fuzztask.py-12992-140229356644096-49-    INFO-"FUZZ检测:   182.92.48.10:80,http"
[2018-08-27 Mon 16:28:57]fuzztask.py-12992-140229356644096-53-    INFO-"Thread-82FUZZ检测任务结束2018-08-27 16:28:57.737698"
[2018-08-27 Mon 16:28:59]fuzzdetect.py-12992-140229360850688-179-   ERROR-"[ERROR] Fail to connect to 113.105.74.144:80"
[2018-08-27 Mon 16:28:59]fuzztask.py-12992-140229360850688-53-    INFO-"Thread-81FUZZ检测任务结束2018-08-27 16:28:59.824093"
[2018-08-27 Mon 16:45:43]fuzztask.py-14028-140163731191552-34-    INFO-"Thread-36 FUZZ检测任务启动2018-08-27 16:45:43.750186"
[2018-08-27 Mon 16:45:43]fuzztask.py-14028-140163730134784-34-    INFO-"Thread-37 FUZZ检测任务启动2018-08-27 16:45:43.920584"
[2018-08-27 Mon 16:45:44]fuzztask.py-14028-140163731191552-49-    INFO-"FUZZ检测:   113.105.74.144:80,http"
[2018-08-27 Mon 16:45:44]fuzztask.py-14028-140163730134784-49-    INFO-"FUZZ检测:   182.92.48.10:80,http"
[2018-08-27 Mon 16:45:48]fuzztask.py-14028-140163730134784-53-    INFO-"Thread-37FUZZ检测任务结束2018-08-27 16:45:48.601344"
[2018-08-27 Mon 16:45:54]fuzzdetect.py-14028-140163731191552-179-   ERROR-"[ERROR] Fail to connect to 113.105.74.144:80"
[2018-08-27 Mon 16:45:54]fuzztask.py-14028-140163731191552-53-    INFO-"Thread-36FUZZ检测任务结束2018-08-27 16:45:54.223945"
[2018-08-27 Mon 16:48:04]fuzztask.py-14028-140163730134784-34-    INFO-"Thread-37 FUZZ检测任务启动2018-08-27 16:48:04.241607"
[2018-08-27 Mon 16:48:04]fuzztask.py-14028-140163730134784-49-    INFO-"FUZZ检测:   182.92.48.10:80,tcpwrapped"
[2018-08-27 Mon 16:48:04]fuzzdetect.py-14028-140163730134784-179-   ERROR-"[ERROR] Fail to connect to 182.92.48.10:80"
[2018-08-27 Mon 16:48:04]fuzztask.py-14028-140163730134784-53-    INFO-"Thread-37FUZZ检测任务结束2018-08-27 16:48:04.499155"
[2018-08-27 Mon 16:56:53]fuzztask.py-14449-140638304798464-34-    INFO-"Thread-36 FUZZ检测任务启动2018-08-27 16:56:53.028161"
[2018-08-27 Mon 16:56:53]fuzztask.py-14449-140638304798464-49-    INFO-"FUZZ检测:   182.92.48.10:80,tcpwrapped"
[2018-08-27 Mon 16:56:53]fuzzdetect.py-14449-140638304798464-179-   ERROR-"[ERROR] Fail to connect to 182.92.48.10:80"
[2018-08-27 Mon 16:56:53]fuzztask.py-14449-140638304798464-53-    INFO-"Thread-36FUZZ检测任务结束2018-08-27 16:56:53.205581"
